using GraphQL.Types;

namespace DotNetGraphQL.API
{
    ///<summary>
    ///   Identity of object in DifHub. Objects can be identify by globaly unique Id and localy unique name.
    ///</summary>
    public class IdentityGraphType : ObjectGraphType<DotNetGraphQL.Common.Models.Identity>
    {
        public IdentityGraphType()
        {
            Field(x => x.Id).Description(@"Id of the object. It is global unique identificator, optional for minor objects and required for major objects. When object created Id will be generated by backend service.");
            Field(x => x.Name).Description(@"Name of the object. It is textual object identificator, need to be unique inside folder of the object.");
            Field(x => x.Description).Description(@"Description for the object functionality. It is text with specification of object and way it used in application.");
            Field<ListGraphType<TranslationGraphType>>("Translations", resolve: x => x.Source.Translations, description: @"$Translations for the object name, description to different languages. Object can contains as many translations as required by application. Refer to: Structure[]: /Translation/v1");
        }
    }
}

