using System;
using System.Collections.Generic;
using System.Text;

namespace DotNetGraphQL.Common.Enums
{

    /// <summary>
    /// Event type define source of event. #
    /// </summary>
    public enum EventType
    {
        ///Event generated by the clause.
        CUSTOM,
        ///Agreement started.
        STARTED,
        ///Agreement terminated.
        TERMINATED
    }
}
