using System;

namespace DotNetGraphQL.Common.Models
{
    ///<summary>
    ///  Identity of object in DifHub. Objects can be identify by globaly unique Id and localy unique name.
    ///</summary>
    public class Identity
    {
        ///Id of the object. It is global unique identificator, optional for minor objects and required for major objects. When object created Id will be generated by backend service.
        public String Id { get; set; } = String.Empty;
        ///Name of the object. It is textual object identificator, need to be unique inside folder of the object.
        public String Name { get; set; } = string.Empty;
        ///Description for the object functionality. It is text with specification of object and way it used in application.
        public String Description { get; set; } = string.Empty;
        ///$Translations for the object name, description to different languages. Object can contains as many translations as required by application. Refer to: Structure[]: /Translation/v1
        public Translation[] Translations { get; set; } = new Translation[0];
    }
}


